server:
  port: 8002

spring:
  datasource: #数据源配置
    password: 123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库的程序驱动类
    url: jdbc:mysql://localhost:3306/onlinelearning?serverTimezone=GMT%2B8&characterEncoding=UTF-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  profiles:
    active: dev #开发环境
  application:
    name: service_edu

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
